import { Vehicle, User, Booking, Review, Agent, Location } from "./types"

export const vehicles: Vehicle[] = [
  {
    id: "v1",
    name: "Renault Clio",
    brand: "Renault",
    model: "Clio",
    year: 2024,
    category: "economique",
    pricePerDay: 250,
    currency: "MAD",
    images: ["/images/vehicles/clio-1.jpg", "/images/vehicles/clio-2.jpg"],
    description: "Citadine compacte et économique, idéale pour les trajets urbains à Marrakech.",
    specifications: {
      engine: "1.0 TCe 90",
      horsepower: 90,
      torque: "142 Nm",
      drivetrain: "Traction",
      fuelConsumption: "5.2L/100km",
      co2Emissions: "118 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "Caméra de recul", "Android Auto", "Apple CarPlay"],
    available: true,
    location: "Marrakech",
    rating: 4.5,
    reviewCount: 128,
    mileage: 15000,
    fuelType: "essence",
    transmission: "manuelle",
    seats: 5,
    doors: 5,
    luggageCapacity: 300,
    enginePower: "90 ch",
    acceleration: "12.5s (0-100km/h)",
    topSpeed: "180 km/h"
  },
  {
    id: "v2",
    name: "Peugeot 208",
    brand: "Peugeot",
    model: "208",
    year: 2024,
    category: "economique",
    pricePerDay: 280,
    currency: "MAD",
    images: ["/images/vehicles/208-1.jpg", "/images/vehicles/208-2.jpg"],
    description: "Design élégant et technologie de pointe pour une conduite plaisir en ville.",
    specifications: {
      engine: "1.2 PureTech 75",
      horsepower: 75,
      torque: "118 Nm",
      drivetrain: "Traction",
      fuelConsumption: "4.8L/100km",
      co2Emissions: "109 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "Écran tactile", "Android Auto", "Apple CarPlay"],
    available: true,
    location: "Casablanca",
    rating: 4.3,
    reviewCount: 95,
    mileage: 12000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 310,
    enginePower: "75 ch",
    acceleration: "13.2s (0-100km/h)",
    topSpeed: "170 km/h"
  },
  {
    id: "v3",
    name: "Dacia Duster",
    brand: "Dacia",
    model: "Duster",
    year: 2024,
    category: "suv",
    pricePerDay: 450,
    currency: "MAD",
    images: ["/images/vehicles/duster-1.jpg", "/images/vehicles/duster-2.jpg"],
    description: "SUV robuste et polyvalent, parfait pour les aventures sur les pistes marocaines.",
    specifications: {
      engine: "1.5 dCi 115",
      horsepower: 115,
      torque: "260 Nm",
      drivetrain: "4x4",
      fuelConsumption: "5.8L/100km",
      co2Emissions: "152 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "Caméra de recul", "GPS", "Sièges chauffants"],
    available: true,
    location: "Marrakech",
    rating: 4.6,
    reviewCount: 203,
    mileage: 25000,
    fuelType: "diesel",
    transmission: "manuelle",
    seats: 5,
    doors: 5,
    luggageCapacity: 445,
    enginePower: "115 ch",
    acceleration: "10.5s (0-100km/h)",
    topSpeed: "185 km/h"
  },
  {
    id: "v4",
    name: "Volkswagen Golf",
    brand: "Volkswagen",
    model: "Golf",
    year: 2023,
    category: "confort",
    pricePerDay: 550,
    currency: "MAD",
    images: ["/images/vehicles/golf-1.jpg", "/images/vehicles/golf-2.jpg"],
    description: "Berline premium avec finition soignée et technologies avancées.",
    specifications: {
      engine: "2.0 TDI 150",
      horsepower: 150,
      torque: "340 Nm",
      drivetrain: "Traction",
      fuelConsumption: "4.5L/100km",
      co2Emissions: "118 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Toit ouvrant", "Caméra 360°"],
    available: true,
    location: "Casablanca",
    rating: 4.7,
    reviewCount: 167,
    mileage: 18000,
    fuelType: "diesel",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 380,
    enginePower: "150 ch",
    acceleration: "8.8s (0-100km/h)",
    topSpeed: "220 km/h"
  },
  {
    id: "v5",
    name: "Mercedes Classe C",
    brand: "Mercedes-Benz",
    model: "Classe C",
    year: 2024,
    category: "luxe",
    pricePerDay: 1200,
    currency: "MAD",
    images: ["/images/vehicles/mercedes-c-1.jpg", "/images/vehicles/mercedes-c-2.jpg"],
    description: "Berline de luxe alliant élégance, confort et performances exceptionnelles.",
    specifications: {
      engine: "C 200 1.5T",
      horsepower: 204,
      torque: "300 Nm",
      drivetrain: "Traction",
      fuelConsumption: "6.2L/100km",
      co2Emissions: "141 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Intérieur cuir", "Son Harman Kardon"],
    available: true,
    location: "Casablanca",
    rating: 4.8,
    reviewCount: 89,
    mileage: 8000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 455,
    enginePower: "204 ch",
    acceleration: "7.3s (0-100km/h)",
    topSpeed: "240 km/h"
  },
  {
    id: "v6",
    name: "BMW Série 5",
    brand: "BMW",
    model: "Série 5",
    year: 2024,
    category: "luxe",
    pricePerDay: 1500,
    currency: "MAD",
    images: ["/images/vehicles/bmw-5-1.jpg", "/images/vehicles/bmw-5-2.jpg"],
    description: "Berline executive de prestige pour les voyageurs exigeants.",
    specifications: {
      engine: "530i 2.0T",
      horsepower: 252,
      torque: "350 Nm",
      drivetrain: "Propulsion",
      fuelConsumption: "6.8L/100km",
      co2Emissions: "155 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Intérieur cuir", "Affichage tête haute"],
    available: true,
    location: "Rabat",
    rating: 4.9,
    reviewCount: 72,
    mileage: 5000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 530,
    enginePower: "252 ch",
    acceleration: "6.2s (0-100km/h)",
    topSpeed: "250 km/h"
  },
  {
    id: "v7",
    name: "Porsche Cayenne",
    brand: "Porsche",
    model: "Cayenne",
    year: 2023,
    category: "luxe",
    pricePerDay: 2500,
    currency: "MAD",
    images: ["/images/vehicles/cayenne-1.jpg", "/images/vehicles/cayenne-2.jpg"],
    description: "SUV de luxe sportif pour une expérience de conduite unique au Maroc.",
    specifications: {
      engine: "Cayenne 3.0 V6",
      horsepower: 340,
      torque: "450 Nm",
      drivetrain: "Intégral",
      fuelConsumption: "9.4L/100km",
      co2Emissions: "214 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Intérieur cuir", "Suspension pneumatique"],
    available: true,
    location: "Marrakech",
    rating: 4.9,
    reviewCount: 45,
    mileage: 12000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 580,
    enginePower: "340 ch",
    acceleration: "6.1s (0-100km/h)",
    topSpeed: "250 km/h"
  },
  {
    id: "v8",
    name: "Audi Q5",
    brand: "Audi",
    model: "Q5",
    year: 2024,
    category: "suv",
    pricePerDay: 1100,
    currency: "MAD",
    images: ["/images/vehicles/q5-1.jpg", "/images/vehicles/q5-2.jpg"],
    description: "SUV premium alliant confort, technologies et design raffiné.",
    specifications: {
      engine: "40 TDI 2.0",
      horsepower: 204,
      torque: "400 Nm",
      drivetrain: "Intégral Quattro",
      fuelConsumption: "5.9L/100km",
      co2Emissions: "155 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Intérieur cuir", "Virtual Cockpit"],
    available: true,
    location: "Casablanca",
    rating: 4.7,
    reviewCount: 112,
    mileage: 10000,
    fuelType: "diesel",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 520,
    enginePower: "204 ch",
    acceleration: "8.1s (0-100km/h)",
    topSpeed: "220 km/h"
  },
  {
    id: "v9",
    name: "Renault Captur",
    brand: "Renault",
    model: "Captur",
    year: 2024,
    category: "suv",
    pricePerDay: 400,
    currency: "MAD",
    images: ["/images/vehicles/captur-1.jpg", "/images/vehicles/captur-2.jpg"],
    description: "Crossover compact et stylé, idéal pour la famille en voyage.",
    specifications: {
      engine: "1.3 TCe 140",
      horsepower: 140,
      torque: "240 Nm",
      drivetrain: "Traction",
      fuelConsumption: "5.6L/100km",
      co2Emissions: "128 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "Caméra de recul", "Écran tactile", "Toit panoramique"],
    available: true,
    location: "Marrakech",
    rating: 4.4,
    reviewCount: 156,
    mileage: 20000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 455,
    enginePower: "140 ch",
    acceleration: "9.9s (0-100km/h)",
    topSpeed: "200 km/h"
  },
  {
    id: "v10",
    name: "Ford Mustang",
    brand: "Ford",
    model: "Mustang",
    year: 2023,
    category: "sport",
    pricePerDay: 1800,
    currency: "MAD",
    images: ["/images/vehicles/mustang-1.jpg", "/images/vehicles/mustang-2.jpg"],
    description: "Muscle car iconique pour une conduite sportive inoubliable.",
    specifications: {
      engine: "5.0 V8 GT",
      horsepower: 450,
      torque: "529 Nm",
      drivetrain: "Propulsion",
      fuelConsumption: "12.4L/100km",
      co2Emissions: "282 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "GPS", "Intérieur cuir", "Son premium"],
    available: true,
    location: "Casablanca",
    rating: 4.8,
    reviewCount: 67,
    mileage: 8000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 4,
    doors: 2,
    luggageCapacity: 400,
    enginePower: "450 ch",
    acceleration: "4.6s (0-100km/h)",
    topSpeed: "250 km/h"
  },
  {
    id: "v11",
    name: "Volkswagen Transporter",
    brand: "Volkswagen",
    model: "Transporter",
    year: 2023,
    category: "van",
    pricePerDay: 800,
    currency: "MAD",
    images: ["/images/vehicles/transporter-1.jpg", "/images/vehicles/transporter-2.jpg"],
    description: "Fourgon spacieux pour les besoins professionnels et familiaux.",
    specifications: {
      engine: "2.0 TDI 150",
      horsepower: 150,
      torque: "340 Nm",
      drivetrain: "Traction",
      fuelConsumption: "7.2L/100km",
      co2Emissions: "189 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "Bluetooth", "GPS", "Caméra de recul", "Portes coulissantes"],
    available: true,
    location: "Casablanca",
    rating: 4.5,
    reviewCount: 89,
    mileage: 35000,
    fuelType: "diesel",
    transmission: "automatique",
    seats: 9,
    doors: 5,
    luggageCapacity: 1200,
    enginePower: "150 ch",
    acceleration: "12.0s (0-100km/h)",
    topSpeed: "180 km/h"
  },
  {
    id: "v12",
    name: "Tesla Model 3",
    brand: "Tesla",
    model: "Model 3",
    year: 2024,
    category: "electrique",
    pricePerDay: 900,
    currency: "MAD",
    images: ["/images/vehicles/model3-1.jpg", "/images/vehicles/model3-2.jpg"],
    description: "Berline 100% électrique avec technologie de pointe et autonomie exceptionnelle.",
    specifications: {
      engine: "Électrique",
      horsepower: 283,
      torque: "450 Nm",
      drivetrain: "Propulsion",
      fuelConsumption: "15 kWh/100km",
      co2Emissions: "0 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation", "GPS", "Écran tactile 15\"", "Autopilot", "Supercharge"],
    available: true,
    location: "Casablanca",
    rating: 4.8,
    reviewCount: 134,
    mileage: 15000,
    fuelType: "electrique",
    transmission: "automatique",
    seats: 5,
    doors: 4,
    luggageCapacity: 425,
    enginePower: "283 ch",
    acceleration: "6.1s (0-100km/h)",
    topSpeed: "225 km/h"
  },
  {
    id: "v13",
    name: "Peugeot 308",
    brand: "Peugeot",
    model: "308",
    year: 2024,
    category: "confort",
    pricePerDay: 480,
    currency: "MAD",
    images: ["/images/vehicles/308-1.jpg", "/images/vehicles/308-2.jpg"],
    description: "Berline élégante avec intérieur raffiné et technologies dernière génération.",
    specifications: {
      engine: "1.5 BlueHDi 130",
      horsepower: 130,
      torque: "300 Nm",
      drivetrain: "Traction",
      fuelConsumption: "4.7L/100km",
      co2Emissions: "123 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation bi-zone", "Bluetooth", "GPS", "Intérieur cuir", "Toit ouvrant"],
    available: true,
    location: "Marrakech",
    rating: 4.6,
    reviewCount: 142,
    mileage: 14000,
    fuelType: "diesel",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 412,
    enginePower: "130 ch",
    acceleration: "9.6s (0-100km/h)",
    topSpeed: "210 km/h"
  },
  {
    id: "v14",
    name: "Mercedes Classe GLE",
    brand: "Mercedes-Benz",
    model: "Classe GLE",
    year: 2024,
    category: "suv",
    pricePerDay: 2000,
    currency: "MAD",
    images: ["/images/vehicles/gle-1.jpg", "/images/vehicles/gle-2.jpg"],
    description: "SUV de luxe premium pour un voyage confortable et majestueux.",
    specifications: {
      engine: "GLE 450 3.0T",
      horsepower: 367,
      torque: "500 Nm",
      drivetrain: "Intégral 4MATIC",
      fuelConsumption: "8.9L/100km",
      co2Emissions: "203 g/km",
      EuroClass: "Euro 6d"
    },
    features: ["Climatisation tri-zone", "Bluetooth", "GPS", "Intérieur cuir", "Suspension air"],
    available: true,
    location: "Casablanca",
    rating: 4.9,
    reviewCount: 56,
    mileage: 7000,
    fuelType: "essence",
    transmission: "automatique",
    seats: 5,
    doors: 5,
    luggageCapacity: 630,
    enginePower: "367 ch",
    acceleration: "5.7s (0-100km/h)",
    topSpeed: "250 km/h"
  }
]

export const users: User[] = [
  {
    id: "u1",
    email: "admin@autoloc.ma",
    name: "Admin AutoLoc",
    phone: "+212 6 00 00 00 00",
    role: "admin",
    createdAt: "2024-01-01T00:00:00Z",
    avatar: "/images/avatars/admin.jpg"
  },
  {
    id: "u2",
    email: "agent@autoloc.ma",
    name: "Agent Marrakech",
    phone: "+212 6 11 11 11 11",
    role: "agent",
    createdAt: "2024-01-15T00:00:00Z",
    avatar: "/images/avatars/agent.jpg"
  },
  {
    id: "u3",
    email: "client@example.com",
    name: "Mohammed Alami",
    phone: "+212 6 22 22 22 22",
    role: "client",
    createdAt: "2024-02-01T00:00:00Z",
    avatar: "/images/avatars/client.jpg"
  }
]

export const bookings: Booking[] = [
  {
    id: "b1",
    userId: "u3",
    vehicleId: "v5",
    startDate: "2026-06-20",
    endDate: "2026-06-25",
    pickupLocation: "Marrakech",
    returnLocation: "Marrakech",
    status: "confirmed",
    totalPrice: 6000,
    currency: "MAD",
    insurance: "premium",
    paymentMethod: "card",
    paymentStatus: "completed",
    createdAt: "2026-06-10T10:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
    notes: "Vol Arrivée 14h"
  },
  {
    id: "b2",
    userId: "u3",
    vehicleId: "v1",
    startDate: "2026-06-15",
    endDate: "2026-06-17",
    pickupLocation: "Casablanca",
    returnLocation: "Casablanca",
    status: "completed",
    totalPrice: 500,
    currency: "MAD",
    insurance: "basic",
    paymentMethod: "cash",
    paymentStatus: "completed",
    createdAt: "2026-06-01T14:00:00Z",
    updatedAt: "2026-06-17T18:00:00Z"
  }
]

export const reviews: Review[] = [
  {
    id: "r1",
    userId: "u3",
    vehicleId: "v5",
    bookingId: "b2",
    rating: 5,
    comment: "Voiture exceptionnelle, service impeccable. Je recommande vivement AutoLoc pour la location de véhicules de luxe au Maroc.",
    createdAt: "2026-06-18T10:00:00Z",
    userName: "Mohammed Alami",
    userAvatar: "/images/avatars/client.jpg"
  },
  {
    id: "r2",
    userId: "u3",
    vehicleId: "v1",
    bookingId: "b2",
    rating: 4,
    comment: "Bonne voiture pour le prix, parfait pour se déplacer en ville. Le service client était très réactif.",
    createdAt: "2026-06-18T12:00:00Z",
    userName: "Mohammed Alami",
    userAvatar: "/images/avatars/client.jpg"
  }
]

export const agents: Agent[] = [
  {
    id: "a1",
    userId: "u2",
    agencyName: "AutoLoc Marrakech",
    agencyAddress: "Avenue Mohammed V, Marrakech",
    agencyPhone: "+212 5 24 00 00 00",
    agencyEmail: "marrakech@autoloc.ma",
    licenseNumber: "MA-2024-001",
    vehicles: vehicles.filter(v => v.location === "Marrakech"),
    rating: 4.8,
    reviewCount: 245,
    verified: true
  }
]

export const locations: Location[] = [
  {
    id: "l1",
    name: "Aéroport Marrakech Ménara",
    address: "Aéroport Marrakech Ménara, Marrakech",
    city: "Marrakech",
    country: "Maroc",
    coordinates: {
      lat: 31.6069,
      lng: -8.0363
    },
    operatingHours: "24h/24, 7j/7",
    phone: "+212 5 24 00 00 00"
  },
  {
    id: "l2",
    name: "Aéroport Casablanca Mohammed V",
    address: "Aéroport Casablanca Mohammed V, Casablanca",
    city: "Casablanca",
    country: "Maroc",
    coordinates: {
      lat: 33.3675,
      lng: -7.5898
    },
    operatingHours: "24h/24, 7j/7",
    phone: "+212 5 22 00 00 00"
  },
  {
    id: "l3",
    name: "Centre-ville Rabat",
    address: "Avenue Hassan II, Rabat",
    city: "Rabat",
    country: "Maroc",
    coordinates: {
      lat: 34.0209,
      lng: -6.8416
    },
    operatingHours: "08:00 - 20:00, 7j/7",
    phone: "+212 5 37 00 00 00"
  }
]

export const categories = [
  { id: "economique", name: "Économique", description: "Véhicules compacts et économiques" },
  { id: "confort", name: "Confort", description: "Berlines confortables et élégantes" },
  { id: "luxe", name: "Luxe", description: "Véhicules de prestige et premium" },
  { id: "suv", name: "SUV", description: "Véhicules tout-terrain et crossover" },
  { id: "sport", name: "Sport", description: "Véhicules sportifs et performants" },
  { id: "van", name: "Van", description: "Fourgons et monospaces" },
  { id: "electrique", name: "Électrique", description: "Véhicules 100% électriques" }
]

export const testimonials = [
  {
    id: "t1",
    name: "Sarah Benali",
    role: "Voyageuse d'affaires",
    content: "Service exceptionnel ! La Mercedes Classe C était impeccable pour mes déplacements professionnels à Casablanca.",
    rating: 5,
    avatar: "/images/testimonials/sarah.jpg"
  },
  {
    id: "t2",
    name: "Youssef Mansouri",
    role: "Touriste",
    content: "Location parfaite pour notre road trip à travers le Maroc. Le Dacia Duster a été notre compagnon idéal.",
    rating: 5,
    avatar: "/images/testimonials/youssef.jpg"
  },
  {
    id: "t3",
    name: "Amina Rachid",
    role: "Expatriée",
    content: "Enfin un service de location fiable au Maroc. La Tesla Model 3 m'a permis de découvrir Marrakech en toute sérénité.",
    rating: 4,
    avatar: "/images/testimonials/amina.jpg"
  }
]
